### ISSUE TITLE
can't visite the demo website build on my local pc

### ISSUE THREAD

**Issue by KarrascoJena** [notwaldorf/example-magenta-in-ts#2]
**Hi, Monica**
I am going to build the website to make the music.
So I researched google and Github. And I found magenta.js and your demo git repository.
At that time I am really glad. So I try to follow the readme text.
The project built success but if I visite "127.0.0.1:8080" or "localhost:8080", I can't see anything.
If I refresh that page, there is some text on the CMD window. I don't know that text meaning.
![2019-11-18_2-18-17](https://user-images.githubusercontent.com/54128071/69039763-cc4ddf80-09a9-11ea-91e1-0c7f4c098690.png)
Hope your kindly reply and want to help me.
Thank you.

**Comment by notwaldorf** [comment]
Hmm, I just re-cloned and followed the instructions in the readme, and it works for me. The console errors are fine, except for the last one about the antivirus. Is there a chance you have something running that wont let you access local IPs? What if you go to `http://localhost:8080/` in your browser instead?

Do you see any errors in the browser dev tools?

**Comment by notwaldorf** [comment]
If it works, it should look like this, btw:
<img width="634" alt="Screen Shot 2019-11-18 at 10 27 20 AM" src="https://user-images.githubusercontent.com/1369170/69079050-080a9880-09ee-11ea-8a28-4bbef9a084f8.png">

**Comment by KarrascoJena** [comment]
Hi, Monica.
Thanks for your help and glad for your kindly reply.
I have tried to build the Ubuntu system and run your demo project. That's working very well. But on the windows 10, still not working. I guess that related to my OS environments and cash matter. That's fine.

**Could you help me further?**
Do you have a magenta.js document with a sample code? Actually I am a new JS. At your demo project, I see the **pianorollsvgvisualizer** class. interesting! I have already checked other piano-roll projects but don't use the magentaJS pianorollsvgvisualizer class. Just use another thing and makes their own code. And I am sure your code more professional. I have found that class document. 
`https://tensorflow.github.io/magenta-js/music/classes/_core_visualizer_.pianorollsvgvisualizer.html```
That document is hard for me to understand and get to start.
Would you please give me another document or tutorial? Or have another demo to create the music? It will help me.
I think with your demo project just I can play the music. But I can't create music, save(mid file) and reload I guess.

**Anyway thanks for your help and hope for your kindly reply again!**
Thank you

**Comment by notwaldorf** [comment]
Ah, this is a very weird repo to start with, then, since it's not really a code example (it's an example of building a typescript project). I would recommend the [getting started page](https://magenta.tensorflow.org/get-started/) on our site, the [interactive code](https://hello-magenta.glitch.me/), or the [api docs](https://tensorflow.github.io/magenta-js/music/)
